title: SonoNeuroS
email: sahil.sharma@inserm.fr
description: >- # this means to ignore newlines until "baseurl:"
  Project website for SonoNeuroS,
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://SonoNeuroS.github.io" # the base hostname & protocol for your site
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build settings
plugins:
  - jekyll-feed
